/* eslint-disable @next/next/no-html-link-for-pages -- Native reference links. */
import ReadingLayout from "../../components/ReadingLayout";
import StructuredData from "../../components/StructuredData";
import { archiveCases, archiveRecords, archiveReleases } from "../../lib/archive";
import { absoluteUrl, pageMetadata, SOURCE_CODE_URL } from "../../lib/site";

export const metadata = pageMetadata("Sources, methods and credits", "Where The Redacted Sky's UAP records come from, how cases are grouped, what has been verified, and the credits and licenses that apply.", "/sources");

export default function SourcesPage() {
  return <ReadingLayout><StructuredData value={{ "@context": "https://schema.org", "@type": "AboutPage", name: "Sources, methods and credits", url: absoluteUrl("/sources"), isPartOf: { "@id": absoluteUrl("/#website") } }} /><h1>Sources, methods and credits.</h1><p className="reading-intro">The Redacted Sky is a free, independent way to explore public UAP records. It is not a government website, and its visual reconstructions and editorial selections are not official findings.</p>
    <section><h2>Where the material comes from</h2><p>The primary index is the <a href="https://www.war.gov/UFO/" target="_blank" rel="noreferrer">U.S. government PURSUE archive</a>. Our current collection contains {archiveRecords.length} record rows across {archiveReleases.length} releases, arranged into {archiveCases.length} editorial case files. These are not counts of confirmed sightings.</p><p>For Releases 01–04, <a href="https://pursue.report/" target="_blank" rel="noreferrer">pursue.report</a> supplied descriptions and remote asset metadata where direct retrieval was restricted. For Releases 05–06, the <a href="https://uap.silv.app/" target="_blank" rel="noreferrer">UAP gallery mirror</a> supplied additional descriptions and media URLs. We did not import their ratings or analysis. Mirror-hosted media is labeled separately.</p></section>
    <section><h2>What has been checked</h2><p>Release 01–04 index rows were checked against the official browser-rendered index on July 18, 2026. The 116 Release 05–06 rows were checked on October 1, 2026. The older rows have not been represented as newly reverified.</p><p>Checking index identity does not authenticate the content of a video or prove what it depicts. Mirror-hosted files have not been byte-verified against official originals. Some source hosts restrict embedding; a blocked preview is not by itself a dead link.</p><p>Three Colorado transcripts, LLE-UAP-D002, D003 and D004, have official descriptions but no verified direct PDF link. LLE-UAP-PR004 has conflicting date information in its title and index; the discrepancy remains visible.</p></section>
    <section><h2>What we add, and what we do not</h2><p>We group explicitly connected source records, shorten source descriptions for case summaries, and create paths through the collection. Curated stories explain why a record is interesting; they are not measured popularity rankings or credibility scores.</p><p>Unknown dates and locations stay unknown. A witness reconstruction stays a reconstruction. The 3D forms in Experience are artist interpretations, not recovered objects or measurements from the source footage.</p><p>Case grouping is editorial and can change as better evidence becomes available. Each case page explains its grouping and links to the original records.</p></section>
    <section id="credits"><h2>Credits and reuse</h2><p>Release 01 Chinese descriptions and the community index used for translation matching are from <a href="https://github.com/chinleez/uap-disclosure-2026" target="_blank" rel="noreferrer">chinleez/uap-disclosure-2026</a>, by chinleez, under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">Creative Commons Attribution 4.0 International (CC BY 4.0)</a>. We matched those translations to official record identifiers and incorporated them into our normalized dataset. Our case grouping, English editorial invitations and interface are separate additions. No endorsement by the original contributor is implied.</p><p>This credit does not place the entire archive under CC BY 4.0. Individual government records, third-party material and media retain their own markings and applicable terms. The application code is MIT-licensed.</p><p>The <a href={`${SOURCE_CODE_URL}/blob/main/data/provenance.json`} target="_blank" rel="noreferrer">provenance log</a>, <a href={`${SOURCE_CODE_URL}/blob/main/data/ingest-report.json`} target="_blank" rel="noreferrer">ingestion report</a> and <a href={SOURCE_CODE_URL} target="_blank" rel="noreferrer">project source</a> document the transformations and known limitations.</p></section>
    <section><h2>Found something that needs correcting?</h2><p>Please include the official record ID and the source that supports the correction when reporting it through the <a href={SOURCE_CODE_URL} target="_blank" rel="noreferrer">project repository</a>. Source evidence, display wording and editorial grouping are different kinds of changes.</p></section>
  </ReadingLayout>;
}
