/* eslint-disable @next/next/no-html-link-for-pages -- Native reference links. */
import ReadingLayout from "../../components/ReadingLayout";
import StructuredData from "../../components/StructuredData";
import { archiveCases, archiveRecords, archiveReleases } from "../../lib/archive";
import { absoluteUrl, pageMetadata, SOURCE_CODE_URL } from "../../lib/site";

export const metadata = pageMetadata("Sources, methods and credits", "Where The Redacted Sky's UAP records come from, how cases are grouped, what has been verified, and the credits and licenses that apply.", "/sources");

export default function SourcesPage() {
  return <ReadingLayout><StructuredData value={{ "@context": "https://schema.org", "@type": "AboutPage", name: "Sources, methods and credits", url: absoluteUrl("/sources"), isPartOf: { "@id": absoluteUrl("/#website") } }} /><h1>Sources, methods and credits.</h1><p className="reading-intro">The Redacted Sky is a free, independent way to explore public UAP records. It is not a government website, and its visual reconstructions and editorial selections are not official findings.</p>
    <section><h2>Official records, independently collected</h2><p>Our current descriptions and index fields come directly from the <a href="https://www.war.gov/UFO/" target="_blank" rel="noreferrer">U.S. government PURSUE archive</a>. We recaptured all {archiveRecords.length} rows and their detail panels on October 1, 2026, Pacific time (October 2 UTC).</p><p>There are {archiveReleases.length} releases, arranged into {archiveCases.length} editorial case files. These are not counts of confirmed sightings. Current records contain no community translations, mirror descriptions or mirror-hosted media.</p></section>
    <section><h2>What was verified, and what was not</h2><p>We checked all 38 index pages and all 450 official descriptions. We also replaced 32 mirror-hosted recordings with links read directly from official <a href="https://www.dvidshub.net/" target="_blank" rel="noreferrer">DVIDS</a> players, matching each record identifier.</p><details><summary>Media and document limitations</summary><p>Other first-party file links were retained from the earlier URL catalog. Their initial discovery used community indexes. Keeping an official URL is not the same as newly opening, reading or byte-verifying every file.</p><p>We have not reviewed every PDF page or authenticated what each video depicts. Some hosts restrict embedding; a blocked preview is not by itself a dead link. Three Colorado transcripts, LLE-UAP-D002, D003 and D004, still have no verified direct PDF link. Three FBI renderings use official preview images, labeled as previews.</p><p>LLE-UAP-PR004 has conflicting date information in its title, index and DVIDS page. We keep that discrepancy visible.</p></details></section>
    <section><h2>What we add, and what we do not</h2><p>We group explicitly connected source records, shorten source descriptions for case summaries, and create paths through the collection. Curated stories explain why a record is interesting; they are not measured popularity rankings or credibility scores.</p><p>Unknown dates and locations stay unknown. A witness reconstruction stays a reconstruction. The 3D forms in Experience are artist interpretations, not recovered objects or measurements from the source footage.</p><p>Case grouping is editorial and can change as better evidence becomes available. Each case page explains its grouping and links to the original records.</p></section>
    <section id="credits"><h2>Provenance and reuse</h2><p>Individual materials retain their own markings and applicable terms. Government hosting is not a blanket license for every item. The application code is MIT-licensed.</p><p>The <a href={`${SOURCE_CODE_URL}/blob/main/data/provenance.json`} target="_blank" rel="noreferrer">provenance log</a> and <a href={`${SOURCE_CODE_URL}/blob/main/data/ingest-report.json`} target="_blank" rel="noreferrer">ingestion report</a> record the inputs and known limitations. Earlier datasets remain documented in our <a href={`${SOURCE_CODE_URL}/blob/main/data/source/HISTORICAL-CREDITS.md`} target="_blank" rel="noreferrer">historical credits</a>. Replacing an input does not erase credit for earlier work.</p></section>
    <section><h2>Found something that needs correcting?</h2><p>Please include the official record ID and the source that supports the correction when reporting it through the <a href={SOURCE_CODE_URL} target="_blank" rel="noreferrer">project repository</a>. Source evidence, display wording and editorial grouping are different kinds of changes.</p></section>
  </ReadingLayout>;
}
